# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::YAML; end
module ActiveSupport::StringInquirer; end
module ActiveSupport::TimeWithZone::TZInfo::TimezonePeriod; end
module Config::YAML; end
module T::CompatibilityPatches::RecorderExtensions; end
module Time::TZInfo::Timezone; end
